### ISSUE TITLE
Avoid directly editing styles

### ISSUE THREAD

**Issue by maanlamp** [Timilof/Timilof.github.io#4]
https://github.com/Timilof/web-app-from-scratch-18-19/blob/45efd92c11120da3e1dcd2af444374787b71d789/week1/public/js/app.js#L56

Maybe use CSS variables in conjunction with `element.style.setProperty()`?

CSS
```css
.naam {
  background-color: var(--backgroundcolor);
}
```
JS
```js
container.querySelectorAll(".naam").forEach((name) => {
  name.addEventListener("click", function() {
    this.style.setProperty("--backgroundcolor", "lime")
  })
})
```
